server:
  port: 8888
app:
  service:
    auth-url: http://ec-secure-gateway
  jwt:
    accesskey: 'CREATEDBYSUJIN_AT'
  open-api: /auth,/authenticate
  authenticated-api: customer-service, process-service, topic-service, menu-service
spring:
  data:
    mongodb:
      uri: "mongodb://13.125.242.146:29999"
      database: "bigdata-analytics-platform"
  application:
    name: ec-api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://zone1:7979/eureka,http://zone2:7878/eureka,http://zone3:7070/eureka