server:
  port: 7979
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7979/eureka
    registerWithEureka: false
    fetchRegistry: false