version: '2'
services:
  eurekaserver1:
    image: popoya67/eureka
    ports:
      - "7979:7979"
    networks:
      - "public"
  eurekaserver2:
    image: popoya67/eureka
    ports:
      - "7878:7878"
    networks:
      - "public"
  eurekaserver3:
    image: popoya67/eureka
    ports:
      - "7070:7070"
    networks:
      - "public"
  gatewayserver:
    image: popoya67/api-gateway
    ports:
      - "8888:8888"
    networks:
      - "public"
networks:
  public:
    external: true